name: Build Parch ISO
on:
  release:
    push:
      tags:
       - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
      - uses: actions/checkout@v2
      - run: pacman -Sy; pacman --noconfirm -S archiso
      - run: cd iso; mkarchiso -v -w work/ -o out/ ./ -g ${{ secrets.GPGID }}
      - uses: actions/upload-artifact@v2
        with:
          name: Parch Live ISO
          path: /__w/parch-plasma-iso/parch-plasma-iso/iso/out/*.iso
